version: '2'
services:
  redis-primary:
    image: docker.io/bitnami/redis:7.0
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=123456
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'

  redis-secondary:
    image: docker.io/bitnami/redis:7.0
    ports:
      - '6379'
    depends_on:
      - redis-primary
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=123456
      - REDIS_PASSWORD=123123
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  redisinsight:
      image: redislabs/redisinsight:latest
      ports:
        - '8001:8001'
      volumes:
        - 'redis_data:/redisinsight_db' 
volumes:
  redis_data:
    driver: local